name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup 
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 9
        sudo apt install llvm-9-dev clang-9-dev libclang-9-dev
    - name: make
      run: |
        mkdir build
        cd build
        cmake ..
        make
